name: Create PR for Feature Branches

on:
  push:
    branches:
      - 'feature/**'  

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit messages
        id: commits
        run: |
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          git log --oneline develop..HEAD >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: develop
          title: "Feature PR: ${{ github.ref_name }}"
          body: |
            This pull request includes the following commits:

            ${{ steps.commits.outputs.commits }}
          branch: ${{ github.ref_name }}

